name: public_e_commerce_api_dart
description: public E-commerce api dart build by dart in server side
version: 0.0.1
homepage: https://github.com/hatemragab/public_e_commerce_api_dart
author: Hatem Ragab
publish_to: "none"
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  path: ^1.7.0
  palace_validators: ^0.0.3
  dartz: ^0.10.0-nullsafety.1
  mysql1: ^0.19.0
  dart_jsonwebtoken: ^2.0.1
  crypt: ^4.0.1
  palace:
    git:
      url: https://github.com/maxzod/palace

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
